server: "EU_SURVIVAL"
ARGUMENT: "Europe"
worlds:
  overworld:
    world: "world"
    min: 10000
    max: 50000
    center_x: 0
    center_z: 0
  nether:
    world: "world_nether"
    min: 5000
    max: 20000
    center_x: 0
    center_z: 0
  end:
    world: "world_the_end"
    min: 10000
    max: 50000
    center_x: 0
    center_z: 0